### ISSUE TITLE
PyPlot crashes Julia 1.4.2 after Julia MKL is installed

### ISSUE THREAD

**Issue by ChrisNabold** [JuliaPy/PyPlot.jl#490] opened 2020-05-26 06:41 UTC
_
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.2 (2020-05-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.4) pkg> add PyPlot
    Cloning default registries into `C:\Users\Chris\.julia`
    Cloning registry from "https://github.com/JuliaRegistries/General.git"
      Added registry `General` to `C:\Users\Chris\.julia\registries\General`
  Resolving package versions...
  Installed Reexport ---------- v0.2.0
  Installed LaTeXStrings ------ v1.1.0
  Installed FixedPointNumbers - v0.8.0
  Installed PyPlot ------------ v2.9.0
  Installed MacroTools -------- v0.5.5
  Installed JSON -------------- v0.21.0
  Installed PyCall ------------ v1.91.4
  Installed ColorTypes -------- v0.10.3
  Installed VersionParsing ---- v1.2.0
  Installed Conda ------------- v1.4.1
  Installed Parsers ----------- v1.0.4
  Installed Colors ------------ v0.12.1
   Updating `C:\Users\Chris\.julia\environments\v1.4\Project.toml`
  [d330b81b] + PyPlot v2.9.0
   Updating `C:\Users\Chris\.julia\environments\v1.4\Manifest.toml`
  [3da002f7] + ColorTypes v0.10.3
  [5ae59095] + Colors v0.12.1
  [8f4d0f93] + Conda v1.4.1
  [53c48c17] + FixedPointNumbers v0.8.0
  [682c06a0] + JSON v0.21.0
  [b964fa9f] + LaTeXStrings v1.1.0
  [1914dd2f] + MacroTools v0.5.5
  [69de0a69] + Parsers v1.0.4
  [438e738f] + PyCall v1.91.4
  [d330b81b] + PyPlot v2.9.0
  [189a3867] + Reexport v0.2.0
  [81def892] + VersionParsing v1.2.0
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8ba89e20] + Distributed
  [b77e0a4c] + InteractiveUtils
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
   Building Conda -? `C:\Users\Chris\.julia\packages\Conda\3rPhK\deps\build.log`
   Building PyCall ? `C:\Users\Chris\.julia\packages\PyCall\zqDXB\deps\build.log`

(@v1.4) pkg> ^C

julia> using PyPlot
[ Info: Precompiling PyPlot [d330b81b-6aea-500a-939a-2ce795aea3ee]
[ Info: Installing matplotlib via the Conda matplotlib package...
[ Info: Running `conda install -y matplotlib` in root environment
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\Chris\.julia\conda\3

  added / updated specs:
    - matplotlib

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cycler-0.10.0              |           py37_0          13 KB
    freetype-2.9.1             |       ha9979f8_1         450 KB
    icu-58.2                   |       ha925a31_3         9.4 MB
    intelpython-2020.1         |                0         502 KB  intel
    jpeg-9b                    |       hb83a4c4_2         245 KB
    kiwisolver-1.2.0           |   py37h74a9793_0          55 KB
    libpng-1.6.37              |       h2a8f88b_0         333 KB
    matplotlib-3.1.3           |           py37_0          22 KB
    matplotlib-base-3.1.3      |   py37h64f37c6_0         4.9 MB
    pyparsing-2.4.7            |             py_0          65 KB
    pyqt-5.9.2                 |   py37h6538335_2         3.3 MB
    python-dateutil-2.8.1      |             py_0         215 KB
    qt-5.9.7                   |   vc14h73c81de_0        72.5 MB
    sip-4.19.8                 |   py37h6538335_0         262 KB
    tornado-6.0.4              |   py37he774522_1         604 KB
    zlib-1.2.11.1              |   vc14hfa6e2cd_1         351 KB  intel
    ------------------------------------------------------------
                                           Total:        93.1 MB

The following NEW packages will be INSTALLED:

  cycler             pkgs/main/win-64::cycler-0.10.0-py37_0
  freetype           pkgs/main/win-64::freetype-2.9.1-ha9979f8_1
  icu                pkgs/main/win-64::icu-58.2-ha925a31_3
  intelpython        intel/win-64::intelpython-2020.1-0
  jpeg               pkgs/main/win-64::jpeg-9b-hb83a4c4_2
  kiwisolver         pkgs/main/win-64::kiwisolver-1.2.0-py37h74a9793_0
  libpng             pkgs/main/win-64::libpng-1.6.37-h2a8f88b_0
  matplotlib         pkgs/main/win-64::matplotlib-3.1.3-py37_0
  matplotlib-base    pkgs/main/win-64::matplotlib-base-3.1.3-py37h64f37c6_0
  pyparsing          pkgs/main/noarch::pyparsing-2.4.7-py_0
  pyqt               pkgs/main/win-64::pyqt-5.9.2-py37h6538335_2
  python-dateutil    pkgs/main/noarch::python-dateutil-2.8.1-py_0
  qt                 pkgs/main/win-64::qt-5.9.7-vc14h73c81de_0
  sip                pkgs/main/win-64::sip-4.19.8-py37h6538335_0
  tornado            pkgs/main/win-64::tornado-6.0.4-py37he774522_1
  zlib               intel/win-64::zlib-1.2.11.1-vc14hfa6e2cd_1

Downloading and Extracting Packages
libpng-1.6.37        | 333 KB    | ############################################################################ | 100%
pyparsing-2.4.7      | 65 KB     | ############################################################################ | 100%
matplotlib-base-3.1. | 4.9 MB    | ############################################################################ | 100%
icu-58.2             | 9.4 MB    | ############################################################################ | 100%
freetype-2.9.1       | 450 KB    | ############################################################################ | 100%
qt-5.9.7             | 72.5 MB   | ############################################################################ | 100%
kiwisolver-1.2.0     | 55 KB     | ############################################################################ | 100%
zlib-1.2.11.1        | 351 KB    | ############################################################################ | 100%
intelpython-2020.1   | 502 KB    | ############################################################################ | 100%
pyqt-5.9.2           | 3.3 MB    | ############################################################################ | 100%
matplotlib-3.1.3     | 22 KB     | ############################################################################ | 100%
jpeg-9b              | 245 KB    | ############################################################################ | 100%
tornado-6.0.4        | 604 KB    | ############################################################################ | 100%
cycler-0.10.0        | 13 KB     | ############################################################################ | 100%
sip-4.19.8           | 262 KB    | ############################################################################ | 100%
python-dateutil-2.8. | 215 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

julia> x = range(0; stop=2*pi, length=1000); y = sin.(3 * x + 4 * cos.(2 * x));

julia> plot(x, y, color="red", linewidth=2.0, linestyle="--")
1-element Array{PyCall.PyObject,1}:
 PyObject <matplotlib.lines.Line2D object at 0x000000003AB3F708>

julia> title("A sinusoidally modulated sinusoid")
PyObject Text(0.5, 1, 'A sinusoidally modulated sinusoid')

(@v1.4) pkg> add https://github.com/JuliaComputing/MKL.jl
    Cloning git-repo `https://github.com/JuliaComputing/MKL.jl`
   Updating git-repo `https://github.com/JuliaComputing/MKL.jl`
  Resolving package versions...
  Installed MKL_jll --------- v2020.1.216+0
  Installed IntelOpenMP_jll - v2018.0.3+0
  Installed PackageCompiler - v1.1.1
   Updating `C:\Users\Chris\.julia\environments\v1.4\Project.toml`
  [33e6dc65] + MKL v0.2.0 #master (https://github.com/JuliaComputing/MKL.jl)
   Updating `C:\Users\Chris\.julia\environments\v1.4\Manifest.toml`
  [1d5cc7b8] + IntelOpenMP_jll v2018.0.3+0
  [33e6dc65] + MKL v0.2.0 #master (https://github.com/JuliaComputing/MKL.jl)
  [856f044c] + MKL_jll v2020.1.216+0
  [9b87118b] + PackageCompiler v1.1.1
   Building MKL ? `C:\Users\Chris\.julia\packages\MKL\1edTo\deps\build.log`

(@v1.4) pkg> add LinearAlgebra
  Resolving package versions...
   Updating `C:\Users\Chris\.julia\environments\v1.4\Project.toml`
  [37e2e46d] + LinearAlgebra
   Updating `C:\Users\Chris\.julia\environments\v1.4\Manifest.toml`
 [no changes]

(@v1.4) pkg> ^C

julia> exit()
------------------------------------

using PyPlot
x = range(0; stop=2*pi, length=1000); y = sin.(3 * x + 4 * cos.(2 * x));
plot(x, y, color="red", linewidth=2.0, linestyle="--") ---> Julia windows 
suddenly closes

**Comment by stevengj** [comment] 2020-05-28 02:03
Duplicate of JuliaPy/PyCall.jl#443

**Closed by stevengj** 2020-05-28 02:03 UTC
