### ISSUE TITLE
PyPlot Julia v0.7 on macOS not working

### ISSUE THREAD

**Issue by stumarcus576** [JuliaPy/PyPlot.jl#434] opened 2019-04-14 21:37 UTC
When I run the test example on the Pyplot.jl page, I get the following error:

2019-04-14 16:29:49.518 julia[55472:37704296] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7ff6cc573250
2019-04-14 16:29:49.519 julia[55472:37704296] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7ff6cc573250'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff4353cded __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff6f604720 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff435ba195 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff434dea60 ___forwarding___ + 1486
	4   CoreFoundation                      0x00007fff434de408 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x000000013dba731d TkpInit + 413
	6   libtk8.6.dylib                      0x000000013daff17e Initialize + 2622
	7   _tkinter.cpython-37m-darwin.so      0x000000013d0eea0f _tkinter_create + 1183
	8   libpython3.7m.dylib                 0x000000012aa252b9 _PyMethodDef_RawFastCallKeywords + 681
	9   libpython3.7m.dylib                 0x000000012aa253bd _PyCFunction_FastCallKeywords + 45
	10  libpython3.7m.dylib                 0x000000012ab2ec4b call_function + 603
	11  libpython3.7m.dylib                 0x000000012ab25e45 _PyEval_EvalFrameDefault + 7893
	12  libpython3.7m.dylib                 0x000000012ab23ad9 _PyEval_EvalCodeWithName + 3305
	13  libpython3.7m.dylib                 0x000000012aa241b1 _PyFunction_FastCallDict + 481
	14  libpython3.7m.dylib                 0x000000012aa25ba4 _PyObject_Call_Prepend + 164
	15  libpython3.7m.dylib                 0x000000012aa8d5aa slot_tp_init + 298
	16  libpython3.7m.dylib                 0x000000012aa96ca7 type_call + 295
	17  libpython3.7m.dylib                 0x000000012aa24e73 _PyObject_FastCallKeywords + 691
	18  libpython3.7m.dylib                 0x000000012ab2ecb4 call_function + 708
	19  libpython3.7m.dylib                 0x000000012ab25f6c _PyEval_EvalFrameDefault + 8188
	20  libpython3.7m.dylib                 0x000000012aa24a6e function_code_fastcall + 254
	21  libpython3.7m.dylib                 0x000000012ab2ecbe call_function + 718
	22  libpython3.7m.dylib                 0x000000012ab25e45 _PyEval_EvalFrameDefault + 7893
	23  libpython3.7m.dylib                 0x000000012ab23ad9 _PyEval_EvalCodeWithName + 3305
	24  libpython3.7m.dylib                 0x000000012aa241b1 _PyFunction_FastCallDict + 481
	25  libpython3.7m.dylib                 0x000000012aa25ba4 _PyObject_Call_Prepend + 164
	26  libpython3.7m.dylib                 0x000000012aa275b4 method_call + 36
	27  libpython3.7m.dylib                 0x000000012aa255b6 PyObject_Call + 246
	28  libpython3.7m.dylib                 0x000000012ab261b5 _PyEval_EvalFrameDefault + 8773
	29  libpython3.7m.dylib                 0x000000012ab23ad9 _PyEval_EvalCodeWithName + 3305
	30  libpython3.7m.dylib                 0x000000012aa241b1 _PyFunction_FastCallDict + 481
	31  ???                                 0x000000012a629b8e 0x0 + 5006072718
	32  ???                                 0x000000012a63e6b7 0x0 + 5006157495
	33  ???                                 0x000000012a645b18 0x0 + 5006187288
	34  libjulia.0.7.0.dylib                0x000000010ca89833 jl_fptr_trampoline + 51
	35  ???                                 0x000000012a645a26 0x0 + 5006187046
	36  libjulia.0.7.0.dylib                0x000000010ca9a1c2 jl_f__apply + 1218
	37  libjulia.0.7.0.dylib                0x000000010ca9a65f jl_f__apply_latest + 63
	38  ???                                 0x000000012a6455f5 0x0 + 5006185973
	39  ???                                 0x000000012a6433f4 0x0 + 5006177268
	40  ???                                 0x000000012a643534 0x0 + 5006177588
	41  ???                                 0x000000012a642e37 0x0 + 5006175799
	42  ???                                 0x000000012a6072ec 0x0 + 5005931244
)
libc++abi.dylib: terminating with uncaught exception of type NSException

signal (6): Abort trap: 6
in expression starting at no file:0
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 14569001 (Pool: 14566720; Big: 2281); GC: 32
Abort trap: 6

**Comment by stevengj** [comment] 2019-04-18 02:08
Looks like this is a duplicate of #410, which is an upstream problem with tkinter.  Try updating to the latest version of PyPlot, which now defaults to the qt backend instead.

**Closed by stevengj** 2019-04-18 02:08 UTC
