### ISSUE TITLE
PyPlot crash with intel complier installed Linux env 

### ISSUE THREAD

**Issue by bluehope** [JuliaPy/PyPlot.jl#280] opened 2017-02-08 12:25 UTC
I'm running Julia in Ubuntu 16.04 with intel compiler installed.
In this situation, PyPlot continues to crash as below.
Would there be any work round?

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.1-pre+31 (2016-11-17 17:50 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 6a1e339* (82 days old release-0.5)
|__/                   |  x86_64-linux-gnu

julia> using PyPlot

julia> plot(rand(10,1),rand(10,1))

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
mkl_blas_avx2_dgemm_nocopy_anbn_b0 at /home/users1/bluehope/intel_compiler/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64/libmkl_avx2.so (unknown line)
mkl_blas_avx2_xdgemm at /home/users1/bluehope/intel_compiler/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64/libmkl_avx2.so (unknown line)
mkl_blas_dgemm_host at /home/users1/bluehope/intel_compiler/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64/libmkl_intel_thread.so (unknown line)
mkl_blas_dgemm at /home/users1/bluehope/intel_compiler/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64/libmkl_intel_thread.so (unknown line)
DGEMM at /home/users1/bluehope/intel_compiler/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64/libmkl_intel_ilp64.so (unknown line)
cblas_dgemm at /home/users1/bluehope/intel_compiler/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64/libmkl_intel_ilp64.so (unknown line)
gemm at /home/ilan/minonda/conda-bld/numpy-1.11_1484074739075/work/numpy-1.11.3/numpy/core/src/multiarray/cblasfuncs.c:61 [inlined]
cblas_matrixproduct at /home/ilan/minonda/conda-bld/numpy-1.11_1484074739075/work/numpy-1.11.3/numpy/core/src/multiarray/cblasfuncs.c:736
PyArray_MatrixProduct2 at /home/ilan/minonda/conda-bld/numpy-1.11_1484074739075/work/numpy-1.11.3/numpy/core/src/multiarray/multiarraymodule.c:938
array_matrixproduct at /home/ilan/minonda/conda-bld/numpy-1.11_1484074739075/work/numpy-1.11.3/numpy/core/src/multiarray/multiarraymodule.c:2186
call_function at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:4350 [inlined]
PyEval_EvalFrameEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:2987
PyEval_EvalCodeEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:3582
fast_function at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:4445 [inlined]
call_function at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:4370 [inlined]
PyEval_EvalFrameEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:2987
PyEval_EvalCodeEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:3582
function_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/funcobject.c:523
PyObject_Call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2546
call_function_tail at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2578 [inlined]
PyObject_CallFunction at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2602
property_descr_set at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/descrobject.c:1257
_PyObject_GenericSetAttrWithDict at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/object.c:1507
PyObject_SetAttr at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/object.c:1252
PyEval_EvalFrameEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:2253
PyEval_EvalCodeEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:3582
function_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/funcobject.c:523
PyObject_Call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2546
instancemethod_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/classobject.c:2602
PyObject_Call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2546
slot_tp_init at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/typeobject.c:5778
type_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/typeobject.c:765
PyObject_Call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2546
ext_do_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:4664 [inlined]
PyEval_EvalFrameEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:3026
PyEval_EvalCodeEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:3582
function_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/funcobject.c:523
PyObject_Call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2546
ext_do_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:4664 [inlined]
PyEval_EvalFrameEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:3026
PyEval_EvalCodeEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:3582
function_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/funcobject.c:523
PyObject_Call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2546
macro expansion at /home/users1/bluehope/.julia/v0.5/PyCall/src/exception.jl:78 [inlined]
#_pycall#66 at /home/users1/bluehope/.julia/v0.5/PyCall/src/PyCall.jl:550
#pycall#70 at /home/users1/bluehope/.julia/v0.5/PyCall/src/PyCall.jl:572
#figure#7 at /home/users1/bluehope/.julia/v0.5/PyPlot/src/PyPlot.jl:143
figure at /home/users1/bluehope/.julia/v0.5/PyPlot/src/PyPlot.jl:142
jl_call_method_internal at /home/users1/bluehope/work_local/julia_0.5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/users1/bluehope/work_local/julia_0.5/src/gf.c:1945
jl_apply at /home/users1/bluehope/work_local/julia_0.5/src/julia.h:1392 [inlined]
jl_f__apply at /home/users1/bluehope/work_local/julia_0.5/src/builtins.c:547
jl_Function_call at /home/users1/bluehope/.julia/v0.5/PyCall/src/callback.jl:35
unknown function (ip: 0x2b71151b4cdf)
PyObject_Call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2546
do_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:4567 [inlined]
call_function at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:4372 [inlined]
PyEval_EvalFrameEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:2987
PyEval_EvalCodeEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:3582
function_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/funcobject.c:523
PyObject_Call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2546
macro expansion at /home/users1/bluehope/.julia/v0.5/PyCall/src/exception.jl:78 [inlined]
#_pycall#66 at /home/users1/bluehope/.julia/v0.5/PyCall/src/PyCall.jl:550
#pycall#70 at /home/users1/bluehope/.julia/v0.5/PyCall/src/PyCall.jl:572
gcf at /home/users1/bluehope/.julia/v0.5/PyPlot/src/PyPlot.jl:150
unknown function (ip: 0x2b71151e07ef)
jl_call_method_internal at /home/users1/bluehope/work_local/julia_0.5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/users1/bluehope/work_local/julia_0.5/src/gf.c:1945
jl_apply at /home/users1/bluehope/work_local/julia_0.5/src/julia.h:1392 [inlined]
jl_f__apply at /home/users1/bluehope/work_local/julia_0.5/src/builtins.c:547
jl_Function_call at /home/users1/bluehope/.julia/v0.5/PyCall/src/callback.jl:35
unknown function (ip: 0x2b71151b4cdf)
PyObject_Call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2546
do_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:4567 [inlined]
call_function at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:4372 [inlined]
PyEval_EvalFrameEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:2987
PyEval_EvalCodeEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:3582
fast_function at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:4445 [inlined]
call_function at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:4370 [inlined]
PyEval_EvalFrameEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:2987
PyEval_EvalCodeEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:3582
function_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/funcobject.c:523
PyObject_Call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2546
macro expansion at /home/users1/bluehope/.julia/v0.5/PyCall/src/exception.jl:78 [inlined]
#_pycall#66 at /home/users1/bluehope/.julia/v0.5/PyCall/src/PyCall.jl:550
jl_call_method_internal at /home/users1/bluehope/work_local/julia_0.5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/users1/bluehope/work_local/julia_0.5/src/gf.c:1945
jl_apply at /home/users1/bluehope/work_local/julia_0.5/src/julia.h:1392 [inlined]
jl_f__apply at /home/users1/bluehope/work_local/julia_0.5/src/builtins.c:547
_pycall at /home/users1/bluehope/.julia/v0.5/PyCall/src/PyCall.jl:538
jl_call_method_internal at /home/users1/bluehope/work_local/julia_0.5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/users1/bluehope/work_local/julia_0.5/src/gf.c:1945
jl_apply at /home/users1/bluehope/work_local/julia_0.5/src/julia.h:1392 [inlined]
jl_f__apply at /home/users1/bluehope/work_local/julia_0.5/src/builtins.c:547
#pycall#70 at /home/users1/bluehope/.julia/v0.5/PyCall/src/PyCall.jl:572
jl_call_method_internal at /home/users1/bluehope/work_local/julia_0.5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/users1/bluehope/work_local/julia_0.5/src/gf.c:1945
jl_apply at /home/users1/bluehope/work_local/julia_0.5/src/julia.h:1392 [inlined]
jl_f__apply at /home/users1/bluehope/work_local/julia_0.5/src/builtins.c:547
pycall at /home/users1/bluehope/.julia/v0.5/PyCall/src/PyCall.jl:572
jl_call_method_internal at /home/users1/bluehope/work_local/julia_0.5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/users1/bluehope/work_local/julia_0.5/src/gf.c:1945
jl_apply at /home/users1/bluehope/work_local/julia_0.5/src/julia.h:1392 [inlined]
jl_f__apply at /home/users1/bluehope/work_local/julia_0.5/src/builtins.c:547
#plot#85 at /home/users1/bluehope/.julia/v0.5/PyPlot/src/PyPlot.jl:172
jl_call_method_internal at /home/users1/bluehope/work_local/julia_0.5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/users1/bluehope/work_local/julia_0.5/src/gf.c:1945
jl_apply at /home/users1/bluehope/work_local/julia_0.5/src/julia.h:1392 [inlined]
jl_f__apply at /home/users1/bluehope/work_local/julia_0.5/src/builtins.c:547
plot at /home/users1/bluehope/.julia/v0.5/PyPlot/src/PyPlot.jl:169
jl_call_method_internal at /home/users1/bluehope/work_local/julia_0.5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/users1/bluehope/work_local/julia_0.5/src/gf.c:1945
do_call at /home/users1/bluehope/work_local/julia_0.5/src/interpreter.c:66
eval at /home/users1/bluehope/work_local/julia_0.5/src/interpreter.c:190
jl_toplevel_eval_flex at /home/users1/bluehope/work_local/julia_0.5/src/toplevel.c:558 [inlined]
jl_toplevel_eval at /home/users1/bluehope/work_local/julia_0.5/src/toplevel.c:580
jl_toplevel_eval_in_warn at /home/users1/bluehope/work_local/julia_0.5/src/builtins.c:590
eval at ./boot.jl:234
unknown function (ip: 0x2b6f108f350f)
jl_call_method_internal at /home/users1/bluehope/work_local/julia_0.5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/users1/bluehope/work_local/julia_0.5/src/gf.c:1945
eval_user_input at ./REPL.jl:64
unknown function (ip: 0x2b71151aa306)
jl_call_method_internal at /home/users1/bluehope/work_local/julia_0.5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/users1/bluehope/work_local/julia_0.5/src/gf.c:1945
macro expansion at ./REPL.jl:95 [inlined]
#3 at ./event.jl:68
unknown function (ip: 0x2b71151a1b1f)
jl_call_method_internal at /home/users1/bluehope/work_local/julia_0.5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/users1/bluehope/work_local/julia_0.5/src/gf.c:1945
jl_apply at /home/users1/bluehope/work_local/julia_0.5/src/julia.h:1392 [inlined]
start_task at /home/users1/bluehope/work_local/julia_0.5/src/task.c:253
unknown function (ip: 0xffffffffffffffff)
Allocations: 3931501 (Pool: 3930455; Big: 1046); GC: 4
Segmentation fault (core dumped)
```

**Comment by stevengj** [comment] 2017-02-08 13:03
Sounds like a duplicate of #165.   If you build Julia against 64-bit MKL (the Intel Math Kernel Library) and NumPy against 32-bit MKL (the default), it will crash when you combine them. 

Solution: don't build Julia with MKL, use the default Julia build (which links against OpenBLAS).  Or recompile Numpy.  Or compile Julia with the 32-bit MKL.

**Closed by stevengj** 2017-02-08 13:03 UTC
