### ISSUE TITLE
Still find segmentation fault, using Julia and MKL

### ISSUE THREAD

**Issue by NoelAraujo** [JuliaPy/PyPlot.jl#385] opened 2018-08-31 18:22 UTC
Using official binary files from Julia downloads, PyPlot works as expected.
I've compiled Julia from source using MKL, and I still gets the message:

```
julia> using PyPlot
julia> x = 1:10;
julia> plot(x)
signal (11): Segmentation fault

signal (11): Segmentation fault
in expression starting at no filein expression starting at no file:0
in expression starting at no file:0
in expression starting at no file:0

signal (11): Segmentation fault
in expression starting at no file:0
Segmentation fault (core dumped)
```

**Comment by braydenware** [comment] 2018-10-10 18:34
I get the same issue with my build of Julia 1.0.1 using MKL. I haven't tried yet with official binaries.

**Comment by stevengj** [comment] 2018-10-10 18:41
Duplicate of #100, #165.  As explained there, this is not a PyPlot issue.  The problem is that you are linking two incompatible versions of MKL.

**Closed by stevengj** 2018-10-10 18:41 UTC

**Comment by stevengj** [comment] 2018-10-10 18:42
Also duplicate of JuliaPy/PyCall.jl#443
