### ISSUE TITLE
PyPlot stopped working on Mac: "No working GUI backend found for matplotlib."

### ISSUE THREAD

**Issue by samdeetwo** [JuliaPy/PyPlot.jl#270] opened 2017-01-10 09:26 UTC
Hello 
Re running some code I worked on, and which worked well before the new year, and now when calling PyPlot I get the following warning:
```
using Plots
pyplot()
```

> WARNING: No working GUI backend found for matplotlib.
> /Users/Samuel/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/__init__.py:1357: UserWarning:  This call to matplotlib.use() has no effect
> because the backend has already been chosen;
> matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
> or matplotlib.backends is imported for the first time.
> 
>  warnings.warn(_use_error_msg)

I have tried some of the previous issues solutions to no avail. I have also uninstalled and reinstalled Anaconda3, still no change. Any idea?
Thanks!

....Addendum: 
Some added warning and error messages form using plots from the command line:

julia> using Plots

julia> plot(sin, -2pi, pi, label="sine function")
WARNING: No working GUI backend found for matplotlib.
/Users/Samuel/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/__init__.py:1357: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
ERROR: PyError (:PyObject_Call) <type 'exceptions.TypeError'>
TypeError('__init__() takes exactly 2 arguments (1 given)',)
  File "/Users/Samuel/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/pyplot.py", line 586, in gcf
    return figure()
  File "/Users/Samuel/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/Users/Samuel/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/Users/Samuel/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/Users/Samuel/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 76, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/Users/Samuel/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)

 in pyerr_check at /Users/Samuel/.julia/v0.5/PyCall/src/exception.jl:56 [inlined]
 in pyerr_check at /Users/Samuel/.julia/v0.5/PyCall/src/exception.jl:61 [inlined]
 in macro expansion at /Users/Samuel/.julia/v0.5/PyCall/src/exception.jl:81 [inlined]
 in #_pycall#66(::Array{Any,1}, ::Function, ::PyCall.PyObject) at /Users/Samuel/.julia/v0.5/PyCall/src/PyCall.jl:546
 in #pycall#70(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Type{PyCall.PyAny}) at /Users/Samuel/.julia/v0.5/PyCall/src/PyCall.jl:568
 in gcf() at /Users/Samuel/.julia/v0.5/PyPlot/src/PyPlot.jl:377
 in _create_backend_figure(::Plots.Plot{Plots.PyPlotBackend}) at /Users/Samuel/.julia/v0.5/Plots/src/backends/pyplot.jl:378
 in _plot_setup(::Plots.Plot{Plots.PyPlotBackend}, ::Dict{Symbol,Any}, ::Array{Dict{Symbol,Any},1}) at /Users/Samuel/.julia/v0.5/Plots/src/pipeline.jl:216
 in _plot!(::Plots.Plot{Plots.PyPlotBackend}, ::Dict{Symbol,Any}, ::Tuple{Base.#sin,Float64,Irrational{:π}}) at /Users/Samuel/.julia/v0.5/Plots/src/plot.jl:198
 in #plot#258(::Array{Any,1}, ::Function, ::Function, ::Vararg{Any,N}) at /Users/Samuel/.julia/v0.5/Plots/src/plot.jl:52
 in (::Plots.#kw##plot)(::Array{Any,1}, ::Plots.#plot, ::Function, ::Float64, ::Vararg{Any,N}) at ./<missing>:0

julia>

**Comment by BoundaryValueProblems** [comment] 2017-01-11 05:19
I have exactly the same problem. It just stopped working today in fact.

**Comment by krzakala** [comment] 2017-01-11 11:10
Brand new mac, same things. 
I tried using both anaconda and the local miniconda instalation, but can't make it work

```
using PyPlot
WARNING: No working GUI backend found for matplotlib.
/Users/florent/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/__init__.py:1357: UserWarning:  This call to matplotlib.use() has no effect
```

**Comment by krzakala** [comment] 2017-01-11 19:24
It could be a duplicate of #259 ?

**Comment by krzakala** [comment] 2017-01-11 21:05
OK, I found a solution by editing the matplotlibrc file
I found its location via
using PyCall
pyimport("matplotlib")["matplotlib_fname"]()

Then I changed 
backend      : macosx
by
backend      : TkAgg

**Comment by BoundaryValueProblems** [comment] 2017-01-11 21:28
krzakala, thank you very much! It works for me now after revising that particular matplotlibrc.
But a question remains: what change in which code(s) caused this problem?  The previous version of matplotlibrc dated September 20, 2016 containing ```backend : macosx``` has been fine until yesterday or so.

**Comment by samdeetwo** [comment] 2017-01-12 12:42
krzakala: thanks so much. It works for me. I agree with BoundaryValueProblems that there remains the puzzle as to why it worked with the other backend a few weeks ago and then stopped.

**Closed** 2017-01-12 12:42 UTC

**Comment by stevengj** [comment] 2017-01-13 18:44
If you use the `macosx` backend in the matplotlibrc, then PyPlot ignores it (it is not supported), and picks its own backend.  I think the default is Qt, and maybe there is a problem with that?

**Comment by BoundaryValueProblems** [comment] 2017-01-13 19:14
stevengj: I'm not sure whether the default is Qt or not on Mac OS X, but I don't have this backends problem due to the matplotlibrc file either on Windows machines or Linux boxes. This seems to me a Mac specific problem.
FYI: on my linux box and on my Windows box, the matplotlibrc has lines: ```backend : Qt5Agg``` and ```backend.qt5 : PyQt5```; note that I never have to modify those matplotlibrc files on linux and Windows.

**Comment by dgleich** [comment] 2017-01-19 01:36
I hosted a Julia install "camp" for my class last night to try and get things working on the mac. At least a few people ran into this issue! We didn't know how to debug it at the time, so a bunch of people left without PyPlot working :( I'm sending this note on to them -- but this is a really annoying issue for new users.

**Comment by BoundaryValueProblems** [comment] 2017-01-19 06:58
By the way, on my mac, I tested to have: ```backend : Qt5Agg``` and ```backend.qt5 : PyQt5``` in that particular matplotlibrc file. It didn't work. So, as of now, the only working backend on mac seems to be ```backend : TkAgg```

**Comment by stevengj** [comment] 2017-01-24 15:38
That's because on Windows and Linux the default is a supported backend (qt) not an unsupported backend (macosx).

**Comment by AidanRocke** [comment] 2017-01-29 16:03
I think the solution of @krzakala should be added to the README.md file under OSX installation. It's just a two line solution so I think there would be no problem adding it to the README. 

Yesterday I encountered this problem for the first time and it was quite frustrating as all the plots which used to work no longer worked.  But, that's problem nowhere nearly as frustrating as what @dgleich encountered.

**Comment by dgleich** [comment] 2017-01-29 18:12
So is this really a bug in the Matplotlib Conda package that we should report somewhere?

**Comment by AidanRocke** [comment] 2017-01-29 18:22
@dgleich I've made a pull request: https://github.com/JuliaPy/PyPlot.jl/pull/277

It might seem like overkill but given the number of old/new Julia users this can affect I think it's worth it.

**Comment by leopoldcambier** [comment] 2017-01-31 00:44
Just to add my 2 cent' : had the same problem today (was all working, restarted my mac, not working anymore : some update ?), and changing backend to "TkAgg" made it work.
