### ISSUE TITLE
using PyPlot -> generates an error now with julia 0.6.0 and 0.6.1

### ISSUE THREAD

**Issue by xgandibleux** [JuliaPy/PyPlot.jl#328] opened 2017-10-28 06:15 UTC
Hi,

I have Julia installed on 2 mac (macOS 10.12.6) since last June. All is perfect on both computers with ver 0.6.0 of Julia.

1) I installed today the ver 0.6.1, and now I have a problem when I invoke “using PyPlot” (see below)
2) back on my current 0.6.0, no problem when I invoke “using PyPlot”

To check if the problem comes or not from my computer, I created a new user account on my mac, I installed v0.6.0 and now I have also this problem with “using PyPlot” ?!?

I swiched on my second computer, I installed 0.6.0 and 0.6.1 => same problem with Pyplot for both versions of Julia. Apparently the problem is not coming from the config of my computers, nor from 0.6.0/0.6.1 but from PyPlot itself, right?

When I installed last June my two environments, nothing has been customized, I just have invoked Pkg.add(“PyPlot”) and using PyPlot
None other package related to plotting needs has been installed.

Is somebody knows this problem and/or has a suggestion to fix it. 
And why this problem occurs now?
Thanks in advance.
Xavier

Pkg.add(“PyPlot”) => no problem raised
using PyPlot =>

julia> using PyPlot
INFO: Precompiling module PyPlot.
INFO: Installing matplotlib via the Conda matplotlib package…
Fetching package metadata …
Solving package specifications: .

Package plan for installation in environment /Users/xavierg/.julia/v0.6/Conda/deps/usr:

The following NEW packages will be INSTALLED:

backports:                     1.0-py27hb4f9756_1    
backports.functools_lru_cache: 1.4-py27h2aca819_1    
backports_abc:                 0.5-py27h6972548_0    
cycler:                        0.10.0-py27hfc73c78_0 
freetype:                      2.8-h143eb01_0        
functools32:                   3.2.3.2-py27h8ceab06_1
libpng:                        1.6.32-hce72d48_2     
matplotlib:                    2.1.0-py27h3078195_0  
pyparsing:                     2.2.0-py27h5bb6aaf_0  
python-dateutil:               2.6.1-py27hd56c96b_1  
pytz:                          2017.2-py27hb891d23_1 
singledispatch:                3.4.0.3-py27he22c18d_0
ssl_match_hostname:            3.5.0.1-py27h8780752_2
subprocess32:                  3.2.7-py27h24b2887_0  
tornado:                       4.5.2-py27h29aec9e_0  

libpng-1.6.32- 100% |################################| Time: 0:00:00 1.26 MB/s
freetype-2.8-h 100% |################################| Time: 0:00:00 1.42 MB/s
backports-1.0- 100% |################################| Time: 0:00:00 2.67 MB/s
backports_abc- 100% |################################| Time: 0:00:00 12.96 MB/s
functools32-3. 100% |################################| Time: 0:00:00 15.96 MB/s
pyparsing-2.2. 100% |################################| Time: 0:00:00 1.59 MB/s
pytz-2017.2-py 100% |################################| Time: 0:00:00 1.56 MB/s
subprocess32-3 100% |################################| Time: 0:00:00 2.62 MB/s
cycler-0.10.0- 100% |################################| Time: 0:00:00 7.32 MB/s
python-dateuti 100% |################################| Time: 0:00:00 1.26 MB/s
singledispatch 100% |################################| Time: 0:00:00 12.84 MB/s
ssl_match_host 100% |################################| Time: 0:00:00 9.83 MB/s
backports.func 100% |################################| Time: 0:00:00 6.13 MB/s
tornado-4.5.2- 100% |################################| Time: 0:00:00 1.33 MB/s
matplotlib-2.1 100% |################################| Time: 0:00:04 1.40 MB/s
ERROR: InitError: PyError (ccall(@pysym(:PyImport_ImportModule), PyPtr, (Cstring,), name)

The Python package mpl_toolkits.mplot3d could not be found by pyimport. Usually this means
that you did not install mpl_toolkits.mplot3d in the Python version being used by PyCall.

PyCall is currently configured to use the Julia-specific Python distribution
installed by the Conda.jl package. To install the mpl_toolkits.mplot3d module, you can
use pyimport_conda("mpl_toolkits.mplot3d", PKG), where PKG is the Anaconda
package the contains the module mpl_toolkits.mplot3d, or alternatively you can use the
Conda package directly (via using Conda followed by Conda.add etcetera).

Alternatively, if you want to use a different Python distribution on your
system, such as a system-wide Python (as opposed to the Julia-specific Python),
you can re-configure PyCall with that Python. As explained in the PyCall
documentation, set ENV[“PYTHON”] to the path/name of the python executable
you want to use, run Pkg.build(“PyCall”), and re-launch Julia.

) <type ‘exceptions.ImportError’>
ImportError(‘No module named mpl_toolkits.mplot3d’,)

Stacktrace:
[1] pyerr_check at /Users/xavierg/.julia/v0.6/PyCall/src/exception.jl:56 [inlined]
[2] pyerr_check at /Users/xavierg/.julia/v0.6/PyCall/src/exception.jl:61 [inlined]
[3] macro expansion at /Users/xavierg/.julia/v0.6/PyCall/src/exception.jl:81 [inlined]
[4] pyimport(::String) at /Users/xavierg/.julia/v0.6/PyCall/src/PyCall.jl:374
[5] init() at /Users/xavierg/.julia/v0.6/PyPlot/src/init.jl:205
[6] _include_from_serialized(::String) at ./loading.jl:157
[7] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
[8] _require(::Symbol) at ./loading.jl:498
[9] require(::Symbol) at ./loading.jl:405
during initialization of module PyPlot

julia>

**Comment by ChrisNabold** [comment] 2017-11-11 15:17
I seem to have the same problem (using Win10/64bit):
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.1 (2017-10-24 22:15 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> ENV["PYTHON"]=""
""

julia> Pkg.build("PyCall")
INFO: Initializing package repository C:\Users\Chris\.julia\v0.6
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
ERROR: PyCall is not an installed package
Stacktrace:
 [1] build!(::Array{String,1}, ::Set{Any}, ::String) at .\pkg\entry.jl:623
 [2] build!(::Array{String,1}, ::Dict{Any,Any}, ::Set{Any}) at .\pkg\entry.jl:635
 [3] build(::Array{String,1}) at .\pkg\entry.jl:650
 [4] (::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#build,Tuple{Array{String,1}}})() at .\pkg\dir.jl:36
 [5] cd(::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#build,Tuple{Array{String,1}}}, ::String) at .\file.jl:59
 [6] #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{String,1}, ::Vararg{Array{String,1},N} where N) at .\pkg\dir.jl:36
 [7] build(::String, ::Vararg{String,N} where N) at .\pkg\pkg.jl:254

julia> Pkg.add("PyPlot")
INFO: Cloning cache of BinDeps from https://github.com/JuliaLang/BinDeps.jl.git
INFO: Cloning cache of ColorTypes from https://github.com/JuliaGraphics/ColorTypes.jl.git
INFO: Cloning cache of Colors from https://github.com/JuliaGraphics/Colors.jl.git
INFO: Cloning cache of Compat from https://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of Conda from https://github.com/JuliaPy/Conda.jl.git
INFO: Cloning cache of FixedPointNumbers from https://github.com/JuliaMath/FixedPointNumbers.jl.git
INFO: Cloning cache of JSON from https://github.com/JuliaIO/JSON.jl.git
INFO: Cloning cache of LaTeXStrings from https://github.com/stevengj/LaTeXStrings.jl.git
INFO: Cloning cache of MacroTools from https://github.com/MikeInnes/MacroTools.jl.git
INFO: Cloning cache of PyCall from https://github.com/JuliaPy/PyCall.jl.git
INFO: Cloning cache of PyPlot from https://github.com/JuliaPy/PyPlot.jl.git
INFO: Cloning cache of Reexport from https://github.com/simonster/Reexport.jl.git
INFO: Cloning cache of SHA from https://github.com/staticfloat/SHA.jl.git
INFO: Cloning cache of URIParser from https://github.com/JuliaWeb/URIParser.jl.git
INFO: Installing BinDeps v0.7.0
INFO: Installing ColorTypes v0.6.6
INFO: Installing Colors v0.8.2
INFO: Installing Compat v0.35.0
INFO: Installing Conda v0.7.0
INFO: Installing FixedPointNumbers v0.4.3
INFO: Installing JSON v0.15.2
INFO: Installing LaTeXStrings v0.3.0
INFO: Installing MacroTools v0.4.0
INFO: Installing PyCall v1.15.0
INFO: Installing PyPlot v2.3.2
INFO: Installing Reexport v0.0.3
INFO: Installing SHA v0.5.2
INFO: Installing URIParser v0.2.0
INFO: Building Conda
INFO: Building PyCall
INFO: Using the Python distribution in the Conda package by default.
To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").
INFO: Downloading miniconda installer ...
INFO: Installing miniconda ...
Warning: 'defaults' already in 'channels' list, moving to the top
Fetching package metadata .................
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Users\Chris\.julia\v0.6\Conda\deps\usr:
#
conda                     4.3.30           py27he817781_0
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment C:\Users\Chris\.julia\v0.6\Conda\deps\usr:

The following NEW packages will be INSTALLED:

    icc_rt:       2017.0.4-h97af966_0
    intel-openmp: 2018.0.0-hcd89f80_7
    mkl:          2018.0.0-h36b65af_4
    numpy:        1.13.3-py27h9ac254c_0

icc_rt-2017.0. 100% |###############################| Time: 0:00:01   5.55 MB/s
intel-openmp-2 100% |###############################| Time: 0:00:00   5.35 MB/s
mkl-2018.0.0-h 100% |###############################| Time: 0:00:30   4.96 MB/s
numpy-1.13.3-p 100% |###############################| Time: 0:00:00   5.23 MB/s
INFO: PyCall is using C:\Users\Chris\.julia\v0.6\Conda\deps\usr\python.exe (Python 2.7.14) at C:\Users\Chris\.julia\v0.6\Conda\deps\usr\python.exe, libpython = C:\Users\Chris\.julia\v0.6\Conda\deps\usr\python27
INFO: C:\Users\Chris\.julia\v0.6\PyCall\deps\deps.jl has been updated
INFO: C:\Users\Chris\.julia\v0.6\PyCall\deps\PYTHON has been updated
INFO: Package database updated

julia> using PyPlot
INFO: Precompiling module PyPlot.
INFO: Installing matplotlib via the Conda matplotlib package...
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment C:\Users\Chris\.julia\v0.6\Conda\deps\usr:

The following NEW packages will be INSTALLED:

    backports:                     1.0-py27h6492d98_1
    backports.functools_lru_cache: 1.4-py27h9586e20_1
    cycler:                        0.10.0-py27h59acbbf_0
    freetype:                      2.8-vc9hf582001_0
    functools32:                   3.2.3.2-py27h0cdbcdb_1
    icu:                           58.2-vc9h3e79e4e_0
    jpeg:                          9b-ha175dff_2
    libpng:                        1.6.32-vc9h2352712_3
    matplotlib:                    2.1.0-py27h86412ea_0
    pyqt:                          5.6.0-py27h224ed30_5
    python-dateutil:               2.6.1-py27hbdcc174_1
    pytz:                          2017.2-py27haecbe8f_1
    qt:                            5.6.2-vc9hc26998b_12
    sip:                           4.18.1-py27h5ec1c1a_2
    sqlite:                        3.20.1-hcee4010_2
    tornado:                       3.1.1-py27_0
    zlib:                          1.2.11-hbc2faf4_2

icu-58.2-vc9h3 100% |###############################| Time: 0:00:04   5.15 MB/s
jpeg-9b-ha175d 100% |###############################| Time: 0:00:00   6.66 MB/s
sqlite-3.20.1- 100% |###############################| Time: 0:00:00   5.91 MB/s
zlib-1.2.11-hb 100% |###############################| Time: 0:00:00   3.87 MB/s
backports-1.0- 100% |###############################| Time: 0:00:00 212.00 kB/s
functools32-3. 100% |###############################| Time: 0:00:00   0.00  B/s
libpng-1.6.32- 100% |###############################| Time: 0:00:00  11.85 MB/s
pytz-2017.2-py 100% |###############################| Time: 0:00:00  12.88 MB/s
sip-4.18.1-py2 100% |###############################| Time: 0:00:00   8.72 MB/s
tornado-3.1.1- 100% |###############################| Time: 0:00:00  11.08 MB/s
cycler-0.10.0- 100% |###############################| Time: 0:00:00 897.39 kB/s
freetype-2.8-v 100% |###############################| Time: 0:00:00  10.05 MB/s
python-dateuti 100% |###############################| Time: 0:00:00   7.82 MB/s
qt-5.6.2-vc9hc 100% |###############################| Time: 0:00:11   5.03 MB/s
backports.func 100% |###############################| Time: 0:00:00 574.69 kB/s
pyqt-5.6.0-py2 100% |###############################| Time: 0:00:00   5.59 MB/s
matplotlib-2.1 100% |###############################| Time: 0:00:01   5.11 MB/s
ERROR: InitError: PyError (ccall(@pysym(:PyImport_ImportModule), PyPtr, (Cstring,), name)

The Python package mpl_toolkits.mplot3d could not be found by pyimport. Usually this means
that you did not install mpl_toolkits.mplot3d in the Python version being used by PyCall.

PyCall is currently configured to use the Julia-specific Python distribution
installed by the Conda.jl package.  To install the mpl_toolkits.mplot3d module, you can
use `pyimport_conda("mpl_toolkits.mplot3d", PKG)`, where PKG is the Anaconda
package the contains the module mpl_toolkits.mplot3d, or alternatively you can use the
Conda package directly (via `using Conda` followed by `Conda.add` etcetera).

Alternatively, if you want to use a different Python distribution on your
system, such as a system-wide Python (as opposed to the Julia-specific Python),
you can re-configure PyCall with that Python.   As explained in the PyCall
documentation, set ENV["PYTHON"] to the path/name of the python executable
you want to use, run Pkg.build("PyCall"), and re-launch Julia.

) <type 'exceptions.ImportError'>
ImportError('No module named mpl_toolkits.mplot3d',)

Stacktrace:
 [1] pyerr_check at C:\Users\Chris\.julia\v0.6\PyCall\src\exception.jl:56 [inlined]
 [2] pyerr_check at C:\Users\Chris\.julia\v0.6\PyCall\src\exception.jl:61 [inlined]
 [3] macro expansion at C:\Users\Chris\.julia\v0.6\PyCall\src\exception.jl:81 [inlined]
 [4] pyimport(::String) at C:\Users\Chris\.julia\v0.6\PyCall\src\PyCall.jl:374
 [5] __init__() at C:\Users\Chris\.julia\v0.6\PyPlot\src\init.jl:205
 [6] _include_from_serialized(::String) at .\loading.jl:157
 [7] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at .\loading.jl:200
 [8] _require(::Symbol) at .\loading.jl:498
 [9] require(::Symbol) at .\loading.jl:405
during initialization of module PyPlot

julia>
I think that the error use in conda Matplotlib has been upgraded to V2.0. On another computer I have an older Julia 0.6.0 installed with Matplotlib - and there PyPlot seem to work ok.

**Comment by algorithmx** [comment] 2017-11-13 16:10
Ubuntu 16.04 with Julia 
++++++++++++++++++++++++++++++++
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.1 (2017-10-24 22:15 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu
++++++++++++++++++++++++++++++++
Installed PyPlot as instructed, got error message after runing plot(rand(10))

ArgumentError: haskey of NULL PyObject

Stacktrace:
 [1] haskey(::PyCall.PyObject, ::String) at /home/yunlong/.julia/v0.6/PyCall/src/PyCall.jl:268
 [2] #plot#85(::Array{Any,1}, ::Function, ::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}, ::Vararg{Any,N} where N) at /home/yunlong/.julia/v0.6/PyPlot/src/PyPlot.jl:169
 [3] (::PyPlot.#kw##plot)(::Array{Any,1}, ::PyPlot.#plot, ::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}, ::Vararg{Any,N} where N) at ./<missing>:0
 [4] include_string(::String, ::String) at ./loading.jl:522

**Comment by mauro3** [comment] 2017-11-24 13:27
I have the same problem.  I installed PyPlot using Conda.jl (on Linux).  The Conda installation of matplotlib seems to work (this uses the Conda.jl python-executable):
```
~/.julia/v0.6/Conda/deps/usr/bin$ ./python
Python 2.7.14 |Anaconda, Inc.| (default, Oct 27 2017, 18:21:12) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pylab as plt
>>> plt.plot([1,2])
[<matplotlib.lines.Line2D object at 0x7f80eaa10b90>]
>>> plt.savefig("tmp2.png")
```
produces the png (using the Agg backend).  

However, PyPlot.jl does not work:
```

   _       _ _(_)_     |  A fresh approach to technical computing
  
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.1 (2017-10-24 22:15 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> using PyPlot
INFO: Recompiling stale cache file ~/.julia/lib/v0.6/PyPlot.ji for module PyPlot.
ERROR: InitError: PyError (ccall(@pysym(:PyImport_ImportModule), PyPtr, (Cstring,), name)

The Python package matplotlib.pyplot could not be found by pyimport. Usually this means
that you did not install matplotlib.pyplot in the Python version being used by PyCall.

PyCall is currently configured to use the Julia-specific Python distribution
installed by the Conda.jl package.  To install the matplotlib.pyplot module, you can
use `pyimport_conda("matplotlib.pyplot", PKG)`, where PKG is the Anaconda
package the contains the module matplotlib.pyplot, or alternatively you can use the
Conda package directly (via `using Conda` followed by `Conda.add` etcetera).

Alternatively, if you want to use a different Python distribution on your
system, such as a system-wide Python (as opposed to the Julia-specific Python),
you can re-configure PyCall with that Python.   As explained in the PyCall
documentation, set ENV["PYTHON"] to the path/name of the python executable
you want to use, run Pkg.build("PyCall"), and re-launch Julia.

) <type 'exceptions.ImportError'>
ImportError("/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by ~/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/../../../libpng16.so.16)",)
  File "~/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "~/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "~/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/contour.py", line 23, in <module>
    import matplotlib.text as text
  File "~/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/text.py", line 33, in <module>
    from matplotlib.backend_bases import RendererBase
  File "~/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 63, in <module>
    import matplotlib.textpath as textpath
  File "~/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/textpath.py", line 20, in <module>
    from matplotlib.mathtext import MathTextParser
  File "~/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/mathtext.py", line 62, in <module>
    import matplotlib._png as _png

Stacktrace:
 [1] pyerr_check at ~/.julia/v0.6/PyCall/src/exception.jl:56 [inlined]
 [2] pyerr_check at ~/.julia/v0.6/PyCall/src/exception.jl:61 [inlined]
 [3] macro expansion at ~/.julia/v0.6/PyCall/src/exception.jl:81 [inlined]
 [4] pyimport(::String) at ~/.julia/v0.6/PyCall/src/PyCall.jl:374
 [5] __init__() at ~/.julia/v0.6/PyPlot/src/init.jl:184
 [6] _include_from_serialized(::String) at ./loading.jl:157
 [7] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [8] _require(::Symbol) at ./loading.jl:464
 [9] require(::Symbol) at ./loading.jl:405
during initialization of module PyPlot
```
The main culprit seems to be `ImportError("/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by ~/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/../../../libpng16.so.16)",)`.  And indeed looking at the libz files in `~/.julia/v0.6/Conda/deps/usr/lib/`:
```
~/.julia/v0.6/Conda/deps/usr/lib$ ls libz.so*
libz.so  libz.so.1  libz.so.1.2.11
```
So it looks like there is a miss-match between the requested zlib-1.2.9 and the installed 1.2.11.

Any pointers on how I should go about debugging this further?

**Comment by stevengj** [comment] 2017-11-28 16:26
Duplicate of #151

**Closed by stevengj** 2017-11-28 16:26 UTC

**Comment by goretkin** [comment] 2017-12-01 18:42
It seems the original errors are regarding
```
ERROR: InitError: PyError (ccall(@pysym(:PyImport_ImportModule), PyPtr, (Cstring,), name)

The Python package mpl_toolkits.mplot3d could not be found by pyimport. Usually this means
that you did not install mpl_toolkits.mplot3d in the Python version being used by PyCall.
```

and not zlib. Is this really a duplicate of #151? 

I was experiencing this error. In the python interpreter used by PyCall, `import mpl_toolkits.mplot3d  ` succeeded. I restarted julia, tried `using PyCall` again, and it worked.

**Comment by mauro3** [comment] 2017-12-01 19:37
The fix https://github.com/JuliaPy/PyPlot.jl/issues/151#issuecomment-287226101 definitely solved my problem. Also using the conda-python, doing `import mpl_toolkits.mplot3d` also succeeds, but that does not change failing `using PyPlot`.
