### ISSUE TITLE
Current (v2.3.2) PyPlot fails installation with private miniconda Python

### ISSUE THREAD

**Issue by oyd11** [JuliaPy/PyPlot.jl#317] opened 2017-10-03 11:41 UTC
I've managed to reproduce a minimal setup of the problem in my setup:

Failing scenario:
I use a docker image for a clean setup:
Dockerfile
```
FROM julia:0.6
```
and try installing PyPlot (v2.3.2) 
```
julia> ENV["PYTHON"]=""
julia> Pkg.add("PyPlot")
# 'ok'
julia> using PyPlot
# failing, not finding 'matplotlib' installed
```

I have a workaround of manually installing an older version of Matplotlib manually using the Conda package before installing PyPlot.jl

Working workaround:
```
Pkg.add("Conda")
using Conda
Conda.add("matplotlib==2.0.1")
Pkg.add("PyPlot.jl")
using PyPlot # ok
```

My guess is - that currently - Conda.jl installs Python 2.7.13, when building "PyPlot.jl" - during the build of "matplotlib" - the installer tries to update to Python 2.7.14, but instead the system ends up having two different Python installations (2.7.13 in Conda, 2.7.14 - with 'matplotlib' built and installed).

Output of the failed run
[ skipping some of the output lines, leave what might be relevant ]
```
julia> ENV["PYTHON"]=""
julia> Pkg.add("PyPlot")
INFO: Initializing package repository /root/.julia/v0.6
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
...
INFO: Cloning cache of PyCall from https://github.com/JuliaPy/PyCall.jl.git
INFO: Cloning cache of PyPlot from https://github.com/JuliaPy/PyPlot.jl.git
...
INFO: Building Conda
INFO: Building PyCall
INFO: Using the Python distribution in the Conda package by default.
To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").
INFO: Downloading miniconda installer ...
...
INFO: Installing miniconda ...
Python 2.7.13 :: Anaconda, Inc.
INFO: PyCall is using /root/.julia/v0.6/Conda/deps/usr/bin/python (Python 2.7.13) at /root/.julia/v0.6/Conda/deps/usr/bin/python, libpython = /root/.julia/v0.6/Conda/deps/usr/lib/libpython2.7
INFO: /root/.julia/v0.6/PyCall/deps/deps.jl has been updated
INFO: /root/.julia/v0.6/PyCall/deps/PYTHON has been updated
INFO: Package database updated

julia> using PyPlot
INFO: Precompiling module PyPlot.
INFO: Installing matplotlib via the Conda matplotlib package...
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /root/.julia/v0.6/Conda/deps/usr:

The following NEW packages will be INSTALLED:
...
matplotlib-2.0 100% |#############################################################################################| Time: 0:00:01   5.06 MB/s
WARNING: No working GUI backend found for matplotlib
ERROR: InitError: PyError (ccall(@pysym(:PyImport_ImportModule), PyPtr, (Cstring,), name)

The Python package matplotlib.pyplot could not be found by pyimport. Usually this means
that you did not install matplotlib.pyplot in the Python version being used by PyCall.

PyCall is currently configured to use the Julia-specific Python distribution
installed by the Conda.jl package.  To install the matplotlib.pyplot module, you can
use `pyimport_conda("matplotlib.pyplot", PKG)`, where PKG is the Anaconda
package the contains the module matplotlib.pyplot, or alternatively you can use the
Conda package directly (via `using Conda` followed by `Conda.add` etcetera).

Alternatively, if you want to use a different Python distribution on your
system, such as a system-wide Python (as opposed to the Julia-specific Python),
you can re-configure PyCall with that Python.   As explained in the PyCall
documentation, set ENV["PYTHON"] to the path/name of the python executable
you want to use, run Pkg.build("PyCall"), and re-launch Julia.

) <type 'exceptions.ImportError'>
ImportError("/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /root/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/../../.././libpng16.so.16)",)
  File "/root/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/root/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "/root/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/contour.py", line 22, in <module>
    import matplotlib.font_manager as font_manager
  File "/root/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/font_manager.py", line 58, in <module>
    from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir

Stacktrace:
 [1] pyerr_check at /root/.julia/v0.6/PyCall/src/exception.jl:56 [inlined]
 [2] pyerr_check at /root/.julia/v0.6/PyCall/src/exception.jl:61 [inlined]
 [3] macro expansion at /root/.julia/v0.6/PyCall/src/exception.jl:81 [inlined]
 [4] pyimport(::String) at /root/.julia/v0.6/PyCall/src/PyCall.jl:374
 [5] __init__() at /root/.julia/v0.6/PyPlot/src/init.jl:184
 [6] _include_from_serialized(::String) at ./loading.jl:157
 [7] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [8] _require(::Symbol) at ./loading.jl:491
 [9] require(::Symbol) at ./loading.jl:398
during initialization of module PyPlot
```

I don't see the Python 2.7.13 -> 2.7.14 prompt in the current run, but it was appearing while I was trying to find a workaround for my system's CI.

**Comment by stevengj** [comment] 2017-10-03 11:57
If you type `Conda.update()` followed by `Pkg.build("PyCall")` does it work?

**Comment by oyd11** [comment] 2017-10-03 14:00
No, Conda.update() for some reason doesn't want to update the Python installation to 2.7.14. 
I think that's the issue - that the 'matplotlib' installer tries to update Python without Conda being aware of it.

**Comment by oyd11** [comment] 2017-10-04 12:43
btw: The error is now different - and my workaround stopped working for now (but the same effect - "out of the box Julia 0.6" - PyPlot.jl - doesn't build. 
Do you guys have a CI for the package where it currently passes? 
The annoying thing - is that the changes - are actually changes to the 'matplotlib' installer (or it's deps), ie, the same version of PyPlot - started failing - on the same Julia version in a 'clean' docker container based on Ubuntu 16

**Comment by oschulz** [comment] 2017-10-05 15:21
I just ran into the same, when switching to Anaconda 5.0.0 (fresh installation):

    $ export PATH="/somedir/julia/bin:/somedir/anaconda2/bin:/usr/bin:/bin"
    $ export JULIA_PKGDIR="/somedir/.julia"
    $ julia
    julia> Pkg.init()
    julia> Pkg.add("PyPlot")
    julia> using PyPlot
    INFO: Precompiling module PyPlot.
    /somedir/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py:1405: UserWarning: 
    This call to matplotlib.use() has no effect because the backend has already
    been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
    or matplotlib.backends is imported for the first time.

      warnings.warn(_use_error_msg)
    WARNING: No working GUI backend found for matplotlib
    ERROR: InitError: PyError (ccall(@pysym(:PyImport_ImportModule), PyPtr, (Cstring,), name)


However, the matplotlib installation itself seems fine:

    $ python
    Python 2.7.13 |Anaconda, Inc.| (default, Sep 22 2017, 00:47:24) 
    [GCC 7.2.0] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import matplotlib.pyplot
    >>> 


When repeat the procedure with Anaconda 4.4.0 (fresh Anaconda install and fresh ".julia" every time), all is fine:

    [...]
    julia> using PyPlot
    INFO: Precompiling module PyPlot.

    julia> 

System information:

* Julia: 0.6.0 (2017-06-19 13:05 UTC), official build, x86_64-pc-linux-gnu
* OS: Ubuntu Linux 16.04, x86_64, Kernel 4.10.0-27-generic

It's not Ubuntu, I get the same in a CentOS-7 Docker/Singularity container.

The weird thing is that the matplotlib version doesn't change much between Anaconda 4.4.0 and 5.5.0.

**Comment by stevengj** [comment] 2017-10-05 15:32
@oschulz, what if you manually set a different backend, e.g. `ENV["MPLBACKEND"]="tkagg"`?

**Comment by oschulz** [comment] 2017-10-05 16:01
@stevengj, I don't have a matplotlibrc (should be in `~/.config/matplotlib`, right?).

`ENV["MPLBACKEND"]="tkagg"` (and `MPLBACKEND=tkagg julia`) doesn't seem to make a difference, either, still getting

    julia> using PyPlot
    /somedir/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py:1405: UserWarning: 
    This call to matplotlib.use() has no effect because the backend has already
    been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
    or matplotlib.backends is imported for the first time.

      warnings.warn(_use_error_msg)
    WARNING: No working GUI backend found for matplotlib
    ERROR: InitError: PyError (ccall(@pysym(:PyImport_ImportModule), PyPtr, (Cstring,), name)

**Comment by oyd11** [comment] 2017-10-08 08:15
So btw: getting " No working GUI backend found for matplotlib" is ok, that's not part of the issue afaik.
The thing is PyPlot.jl installation is a requirement for many packages even when I deploy computational servers (where I don't need any 'working GUI backend') - for example - currently - DSP.jl - requires PyPlot (maybe just for some test or prototyping reasons)
I'll write there maybe these requirements should be factored out

**Comment by stevengj** [comment] 2017-10-10 17:53
If you don't need a GUI, you can use `ENV["MPLBACKEND"]="agg"`.

As far as I can tell, DSP.jl does not require PyPlot (either directly or indirectly via dependencies), so I'm not sure what you're referring to there.

**Comment by Balinus** [comment] 2017-10-16 19:00
I do have the same problem (or appears to be). Locally, my package is testing correctly. When pushed to CI, the error pops out at the line `using PyPlot` inside the module definition.

Here's the command used on .travis.yml file:

`- julia -e 'ENV["PYTHON"]=""; Pkg.add("Conda"); using Conda;  Conda.update(); Conda.add("matplotlib");  Conda.add("basemap"); Pkg.add("PyCall"); Pkg.build("PyCall"); Pkg.add("PyPlot"); Pkg.build("PyPlot");'`

Error on travis-ci (below). The error line is associated with the `using PyPlot`, when the package is being tested, even though the package is installed in the previous command and install correctly.

```
julia -e 'Pkg.test("ClimateTools"; coverage=true)'
INFO: Testing ClimateTools
WARNING: No working GUI backend found for matplotlib
ERROR: LoadError: LoadError: InitError: PyError (ccall(@pysym(:PyImport_ImportModule), PyPtr, (Cstring,), name)
The Python package matplotlib.pyplot could not be found by pyimport. Usually this means
that you did not install matplotlib.pyplot in the Python version being used by PyCall.
PyCall is currently configured to use the Julia-specific Python distribution
installed by the Conda.jl package.  To install the matplotlib.pyplot module, you can
use `pyimport_conda("matplotlib.pyplot", PKG)`, where PKG is the Anaconda
package the contains the module matplotlib.pyplot, or alternatively you can use the
Conda package directly (via `using Conda` followed by `Conda.add` etcetera).
Alternatively, if you want to use a different Python distribution on your
system, such as a system-wide Python (as opposed to the Julia-specific Python),
you can re-configure PyCall with that Python.   As explained in the PyCall
documentation, set ENV["PYTHON"] to the path/name of the python executable
you want to use, run Pkg.build("PyCall"), and re-launch Julia.
) <type 'exceptions.ImportError'>
ImportError("/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/travis/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/../../../libpng16.so.16)",)
  File "/home/travis/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/home/travis/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "/home/travis/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/contour.py", line 23, in <module>
    import matplotlib.text as text
  File "/home/travis/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/text.py", line 33, in <module>
    from matplotlib.backend_bases import RendererBase
  File "/home/travis/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 63, in <module>
    import matplotlib.textpath as textpath
  File "/home/travis/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/textpath.py", line 20, in <module>
    from matplotlib.mathtext import MathTextParser
  File "/home/travis/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/mathtext.py", line 62, in <module>
    import matplotlib._png as _png
Stacktrace:
 [1] pyerr_check at /home/travis/.julia/v0.6/PyCall/src/exception.jl:56 [inlined]
 [2] pyerr_check at /home/travis/.julia/v0.6/PyCall/src/exception.jl:61 [inlined]
 [3] macro expansion at /home/travis/.julia/v0.6/PyCall/src/exception.jl:81 [inlined]
 [4] pyimport(::String) at /home/travis/.julia/v0.6/PyCall/src/PyCall.jl:374
 [5] __init__() at /home/travis/.julia/v0.6/PyPlot/src/init.jl:184
 [6] _include_from_serialized(::String) at ./loading.jl:157
 [7] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [8] _require(::Symbol) at ./loading.jl:491
 [9] require(::Symbol) at ./loading.jl:398
 [10] include_from_node1(::String) at ./loading.jl:569
during initialization of module PyPlot
while loading /home/travis/.julia/v0.6/ClimateTools/src/ClimateTools.jl, in expression starting on line 17
while loading /home/travis/.julia/v0.6/ClimateTools/test/runtests.jl, in expression starting on line 1
```

**Comment by stevengj** [comment] 2017-10-16 19:15
`Python package matplotlib.pyplot could not be found by pyimport` means that something is pretty wrong with your python installation.

Do you have an environment variable like `PYTHONPATH` or `PYTHONHOME` set, which might be confusing Python about the package locations?   (Look in `ENV`).

**Comment by Balinus** [comment] 2017-10-16 19:35
Well, it's not my environment. It's the one on travis-ci.org. Locally, everything is fine when I do a `Pkg.test("ClimateTools")`.

Here's the config file (keeping only the relevant lines). I prescribed specific python and matplotlib version (which does not help -> omitting the specified versions does not change the outcome).

```
# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
matrix:
  - PYTHON=Conda-python
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("ClimateTools");'
  - julia -e 'Pkg.test("ClimateTools"; coverage=true)'
before_install:
  - julia -e 'ENV["PYTHON"]=""; Pkg.add("Conda"); using Conda;  Conda.add("python==2.7.13"); Conda.add("matplotlib==2.0.1"); Conda.add("basemap"); Pkg.add("PyCall"); Pkg.build("PyCall"); Pkg.add("PyPlot");'
```

**Comment by Balinus** [comment] 2017-10-17 12:51
Here's the job log on travis, in case it's useful.

https://travis-ci.org/Balinus/ClimateTools.jl/jobs/288703890

**Comment by floswald** [comment] 2017-10-17 14:29
I'm having the same problem on a linux box.

```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> ENV["PYTHON"]=""
""

julia> Pkg.build("PyCall")
INFO: Building Conda
INFO: Building PyCall
INFO: Using the Python distribution in the Conda package by default.
To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").
INFO: PyCall is using /root/.julia/v0.6/Conda/deps/usr/bin/python (Python 2.7.13) at /root/.julia/v0.6/Conda/deps/usr/bin/python, libpython = /root/.julia/v0.6/Conda/deps/usr/lib/libpython2.7
INFO: /root/.julia/v0.6/PyCall/deps/deps.jl has not changed
INFO: /root/.julia/v0.6/PyCall/deps/PYTHON has not changed

julia> Pkg.build("PyPlot")
INFO: Building Conda
INFO: Building PyCall
INFO: Using the Python distribution in the Conda package by default.
To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").
INFO: PyCall is using /root/.julia/v0.6/Conda/deps/usr/bin/python (Python 2.7.13) at /root/.julia/v0.6/Conda/deps/usr/bin/python, libpython = /root/.julia/v0.6/Conda/deps/usr/lib/libpython2.7
INFO: /root/.julia/v0.6/PyCall/deps/deps.jl has not changed
INFO: /root/.julia/v0.6/PyCall/deps/PYTHON has not changed

julia> using PyPlot
WARNING: No working GUI backend found for matplotlib
ERROR: InitError: PyError (ccall(@pysym(:PyImport_ImportModule), PyPtr, (Cstring,), name)

The Python package matplotlib.pyplot could not be found by pyimport. Usually this means
that you did not install matplotlib.pyplot in the Python version being used by PyCall.

PyCall is currently configured to use the Julia-specific Python distribution
installed by the Conda.jl package.  To install the matplotlib.pyplot module, you can
use `pyimport_conda("matplotlib.pyplot", PKG)`, where PKG is the Anaconda
package the contains the module matplotlib.pyplot, or alternatively you can use the
Conda package directly (via `using Conda` followed by `Conda.add` etcetera).

Alternatively, if you want to use a different Python distribution on your
system, such as a system-wide Python (as opposed to the Julia-specific Python),
you can re-configure PyCall with that Python.   As explained in the PyCall
documentation, set ENV["PYTHON"] to the path/name of the python executable
you want to use, run Pkg.build("PyCall"), and re-launch Julia.

) <type 'exceptions.ImportError'>
ImportError("/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /root/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/../../../libpng16.so.16)",)
  File "/root/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/root/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "/root/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/contour.py", line 23, in <module>
    import matplotlib.text as text
  File "/root/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/text.py", line 33, in <module>
    from matplotlib.backend_bases import RendererBase
  File "/root/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 63, in <module>
    import matplotlib.textpath as textpath
  File "/root/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/textpath.py", line 20, in <module>
    from matplotlib.mathtext import MathTextParser
  File "/root/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/mathtext.py", line 62, in <module>
    import matplotlib._png as _png

Stacktrace:
 [1] pyerr_check at /root/.julia/v0.6/PyCall/src/exception.jl:56 [inlined]
 [2] pyerr_check at /root/.julia/v0.6/PyCall/src/exception.jl:61 [inlined]
 [3] macro expansion at /root/.julia/v0.6/PyCall/src/exception.jl:81 [inlined]
 [4] pyimport(::String) at /root/.julia/v0.6/PyCall/src/PyCall.jl:374
 [5] __init__() at /root/.julia/v0.6/PyPlot/src/init.jl:184
 [6] _include_from_serialized(::String) at ./loading.jl:157
 [7] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [8] _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:236
 [9] _require(::Symbol) at ./loading.jl:434
 [10] require(::Symbol) at ./loading.jl:398
during initialization of module PyPlot

julia> versioninfo()
Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

julia> Pkg.status("PyPlot")
 - PyPlot                        2.3.2

julia> 
```

**Comment by stevengj** [comment] 2017-10-17 17:51
This seems to be the problem:
```
ImportError("/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /root/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/../../../libpng16.so.16)",)
```
This is a duplicate of #151, then?

**Comment by floswald** [comment] 2017-10-17 19:08
yes, that's it!
thanks!

**Comment by Balinus** [comment] 2017-10-17 19:46
Using the following command for travis-ci worked! Thanks.

```
script:
  - LD_PRELOAD=${HOME}/.julia/v0.6/Conda/deps/usr/lib/libz.so julia -e 'Pkg.clone(pwd());Pkg.test("ClimateTools"; coverage=true);'
```

Any idea on how to do the same with Windows? i.e. appveyor.

**Comment by stevengj** [comment] 2017-10-23 18:35
Closing as a duplicate.

**Closed by stevengj** 2017-10-23 18:35 UTC
