### ISSUE TITLE
PyError PyPlot not working under macOSX using conda

### ISSUE THREAD

**Issue by jrekier** [JuliaPy/PyPlot.jl#276] opened 2017-01-24 13:52 UTC
Trying to follow instructions from [here](https://github.com/JuliaPy/PyPlot.jl#automated-matplotlib-installation). Running:
```
ENV["PYTHON"]=""
Pkg.build("PyCall")
```
results in:
```
Pkg.build("PyCall")
INFO: Building Conda
INFO: Building PyCall
INFO: No system-wide Python was found; got the following error:
could not spawn `'' -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: no such file or directory (ENOENT)
using the Python distribution in the Conda package
Fetching package metadata ...
......

Solving package specifications: 
.


# All requested packages already installed.
# packages in environment at /Users/rekierj/.julia/v0.5/Conda/deps/usr:
#
numpy                     1.11.3                   py27_0  
INFO: PyCall is using /Users/rekierj/.julia/v0.5/Conda/deps/usr/bin/python (Python 2.7.13) at /Users/rekierj/.julia/v0.5/Conda/deps/usr/bin/python, libpython = /Users/rekierj/.julia/v0.5/Conda/deps/usr/lib/libpython2.7
INFO: /Users/rekierj/.julia/v0.5/PyCall/deps/deps.jl has not changed
INFO: /Users/rekierj/.julia/v0.5/PyCall/deps/PYTHON has not changed
```

So I assume that conda is in place. 
However, running

```
pyplot()
```
Results in 

```
WARNING: No working GUI backend found for matplotlib.
/Users/rekierj/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
```

If I ignore this and go along with `plot(rand(4,4))`, this results:

```
ERROR: PyError (:PyObject_Call) <type 'exceptions.TypeError'>
TypeError('__init__() takes exactly 2 arguments (1 given)',)
  File "/Users/rekierj/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/pyplot.py", line 586, in gcf
    return figure()
  File "/Users/rekierj/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/Users/rekierj/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/Users/rekierj/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/Users/rekierj/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 76, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/Users/rekierj/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 66, in __init__
    QtWidgets.QWidget.__init__(self)

 in pyerr_check at /Users/rekierj/.julia/v0.5/PyCall/src/exception.jl:56 [inlined]
 in pyerr_check at /Users/rekierj/.julia/v0.5/PyCall/src/exception.jl:61 [inlined]
 in macro expansion at /Users/rekierj/.julia/v0.5/PyCall/src/exception.jl:81 [inlined]
 in #_pycall#66(::Array{Any,1}, ::Function, ::PyCall.PyObject) at /Users/rekierj/.julia/v0.5/PyCall/src/PyCall.jl:546
 in #pycall#70(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Type{PyCall.PyAny}) at /Users/rekierj/.julia/v0.5/PyCall/src/PyCall.jl:568
 in gcf() at /Users/rekierj/.julia/v0.5/PyPlot/src/PyPlot.jl:377
 in _create_backend_figure(::Plots.Plot{Plots.PyPlotBackend}) at /Users/rekierj/.julia/v0.5/Plots/src/backends/pyplot.jl:378
 in _plot_setup(::Plots.Plot{Plots.PyPlotBackend}, ::Dict{Symbol,Any}, ::Array{Dict{Symbol,Any},1}) at /Users/rekierj/.julia/v0.5/Plots/src/pipeline.jl:216
 in _plot!(::Plots.Plot{Plots.PyPlotBackend}, ::Dict{Symbol,Any}, ::Tuple{Array{Float64,2}}) at /Users/rekierj/.julia/v0.5/Plots/src/plot.jl:195
 in plot(::Array{Float64,2}) at /Users/rekierj/.julia/v0.5/Plots/src/plot.jl:46
```

I would love a bit of help to figure that out. 
Some extra information:
I use miniconda outside of julia and the relevant parts of my .bash_profile look like that:
```
...    
export PATH="/Users/rekierj/miniconda3/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
...
```
The variable $PYTHONPATH is left unset.

Any idea ? Thank you very much in advance.

**Comment by ggggggggg** [comment] 2017-01-24 17:41
I have the same problem. 

Here is a temporary workaround that works for me, I haven't figured out the actual problem though.
```
using PyCall
pygui(:tk)
using PyPlot
plot(4)
```

**Comment by jrekier** [comment] 2017-01-25 15:08
This works for me as well. 
Anyway I can get the plot to display in the Juno plot pane ?

**Comment by stevengj** [comment] 2017-02-01 05:09
I can't reproduce this problem.  Have you tried `Pkg.checkout("PyPlot")` to see if the latest (master) version works?

**Comment by ggggggggg** [comment] 2017-02-01 23:27
`Pkg.checkout("PyPlot");using PyPlot;plot(4)` produces an image
`using Conda; Conda.update();Pkg.free("PyPlot");using PyPlot;plot(4)` produces "WARNING: No working GUI backend..."
`Pkg.checkout("PyPlot");using PyPlot;plot(4)` after the conda update produces an image

Thanks,
Sounds like it just needs a new tagged version?

**Comment by stevengj** [comment] 2017-02-04 02:37
Should be fixed now that a new version was tagged.

**Closed by stevengj** 2017-02-04 02:37 UTC
