### ISSUE TITLE
plotting causes SEGFAULT

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaPy/PyPlot.jl#419] opened 2019-01-17 12:21 UTC
```julia
julia> versioninfo()
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.2.0)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

julia> using PyPlot

julia> plot(1:10)
Segmentation fault: 11
```

A window briefly appears before the SEGFAULT.

**Comment by cormullion** [comment] 2019-01-24 09:16
A bit more information from the crash on my mac:

```
julia-1.1> using PyPlot

julia-1.1> x = range(0; stop=2*pi, length=1000); y = sin.(3 * x + 4 * cos.(2 * x));

julia-1.1> plot(x, y, color="red", linewidth=2.0, linestyle="--")
2019-01-24 09:11:10.174 julia[662:29121764] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7fbafd8318c0
2019-01-24 09:11:10.174 julia[662:29121764] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7fbafd8318c0'
*** First throw call stack:
(
)
libc++abi.dylib: terminating with uncaught exception of type NSException

signal (6): Abort trap: 6
in expression starting at no file:0
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 12760827 (Pool: 12759145; Big: 1682); GC: 27
Abort trap: 6
```

using `[d330b81b] PyPlot v2.7.0`

Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)

**Comment by cormullion** [comment] 2019-01-24 09:19
(May be the same as https://github.com/JuliaPy/PyPlot.jl/issues/253.)

**Comment by stevengj** [comment] 2019-01-24 15:14
It works fine for me on my Mac with the Conda Python.  What are `PyPlot.backend` and `PyPlot.PyCall.python`?

**Comment by dlfivefifty** [comment] 2019-01-24 15:17
Exactly the same thing:
```julia
julia> PyPlot.backend
"qt5agg"

julia> PyPlot.PyCall.python
"/Users/solver/.julia/conda/3/bin/python"
```

**Comment by dlfivefifty** [comment] 2019-01-24 15:32
Yes, it works!

**Comment by stevengj** [comment] 2019-01-24 15:48
I still can't reproduce.  I'm using Julia 1.1.0 on macos 10.14, and I ran `Conda.update()` to make sure I'm using the latest Conda packages; can you try that?

**Comment by dlfivefifty** [comment] 2019-01-24 15:55
Just did and still it crashes

**Comment by stevengj** [comment] 2019-01-24 16:11
Are you using JuliaPro or the standard Julia?

**Comment by dlfivefifty** [comment] 2019-01-24 16:12
Julia 1.0.2 built from source with MKL:
```julia
julia> versioninfo()
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.2.0)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

**Comment by stevengj** [comment] 2019-01-24 16:13
Duplicate of JuliaPy/PyCall.jl#443.

Julia's MKL conflicts with the one used in NumPy.

**Closed by stevengj** 2019-01-24 16:13 UTC

**Comment by stevengj** [comment] 2019-01-24 16:16
By the way, what does `LinearAlgebra.BLAS.vendor()` print for such builds?   It might be nice to print a warning.

**Comment by dlfivefifty** [comment] 2019-01-24 16:17
```julia
julia> LinearAlgebra.BLAS.vendor()
:mkl
```

**Comment by stevengj** [comment] 2019-01-24 16:45
Warning added in JuliaPy/PyCall.jl#637
