### ISSUE TITLE
runtime exception on 0.6

### ISSUE THREAD

**Issue by musm** [JuliaPy/PyPlot.jl#272] opened 2017-01-11 23:18 UTC
It seems that it now precompiles on 0.6, but I get runtime exception error now
```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0-dev.2005 (2017-01-09 10:16 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit db4aaa3* (2 days old master)
|__/                   |  x86_64-w64-mingw32

julia> using PyCall
INFO: Recompiling stale cache file C:\Users\Mus\.julia\lib\v0.6\PyCall.ji for module PyCall.

julia> pyimport("matplotlib")["matplotlib_fname"]()
"C:\\Users\\Mus\\.matplotlib\\matplotlibrc"

julia> using PyPlot
INFO: Recompiling stale cache file C:\Users\Mus\.julia\lib\v0.6\PyPlot.ji for module PyPlot.

julia> plot(randn(10))
ERROR: PyError (:PyObject_Call) <class 'RuntimeError'>
RuntimeError('Julia exception: MethodError(PyPlot.gcf,(),0x000000000000506c)',)
  File "C:\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 3154, in plot
    ax = gca()
  File "C:\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 936, in gca
    return gcf().gca(**kwargs)

Stacktrace:
 [1] pyerr_check at C:\Users\Mus\.julia\v0.6\PyCall\src\exception.jl:56 [inlined]
 [2] pyerr_check at C:\Users\Mus\.julia\v0.6\PyCall\src\exception.jl:61 [inlined]
 [3] macro expansion at C:\Users\Mus\.julia\v0.6\PyCall\src\exception.jl:79 [inlined]
 [4] #_pycall#66(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at C:\Users\Mus\.julia\v0.6\PyCall\src\PyCall.jl:546
 [5] _pycall(::PyCall.PyObject, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at C:\Users\Mus\.julia\v0.6\PyCall\src\PyCall.jl:534
 [6] #pycall#70(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Type{PyCall.PyAny}, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at C:\Users\Mus\.julia\v0.6\PyCall\src\PyCall.jl:568
 [7] pycall(::PyCall.PyObject, ::Type{PyCall.PyAny}, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at C:\Users\Mus\.julia\v0.6\PyCall\src\PyCall.jl:568
 [8] #plot#85(::Array{Any,1}, ::Function, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at C:\Users\Mus\.julia\v0.6\PyPlot\src\PyPlot.jl:400
 [9] plot(::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at C:\Users\Mus\.julia\v0.6\PyPlot\src\PyPlot.jl:397

julia> ^C
```

**Comment by giordano** [comment] 2017-01-16 23:04
Duplicate of https://github.com/JuliaPy/PyPlot.jl/issues/269?  Which version of matplotlib do you have?

**Closed** 2017-01-17 21:04 UTC
