### ISSUE TITLE
Cannot plot, ReadOnlyMemoryError

### ISSUE THREAD

**Issue by exit91** [JuliaPy/PyPlot.jl#331] opened 2017-11-04 17:15 UTC
Here's an example session, PyPlots is being called from the Plots.jl package:

```
julia> using Plots
    
julia> pyplot()
Plots.PyPlotBackend()

julia> plot(1:10,1:10)
Error showing value of type Plots.Plot{Plots.PyPlotBackend}:
ERROR: ReadOnlyMemoryError()

julia> # ok, give it another try...

julia> plot(1:10,1:10)
```

At this point an empty (=content not being rendered) window pops up with the title "matplotlib".

Let's try using raw PyPlot.jl and see what happens:

```
julia> using PyPlot

julia> PyPlot.plot(1:10,1:10)
ERROR: PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, C_NULL)) <class 'RuntimeError'>
RuntimeError('Julia exception: ReadOnlyMemoryError()',)                                                                   
  File "/usr/lib/python3.6/site-packages/matplotlib/pyplot.py", line 3229, in plot                                        
    ax = gca()
  File "/usr/lib/python3.6/site-packages/matplotlib/pyplot.py", line 959, in gca
    return gcf().gca(**kwargs)
  File "/usr/lib/python3.6/site-packages/matplotlib/pyplot.py", line 588, in gcf
    return figure()

Stacktrace:
 [1] pyerr_check at /home/long/.julia/v0.6/PyCall/src/exception.jl:56 [inlined]
 [2] pyerr_check at /home/long/.julia/v0.6/PyCall/src/exception.jl:61 [inlined]
 [3] macro expansion at /home/long/.julia/v0.6/PyCall/src/exception.jl:81 [inlined]
 [4] #_pycall#67(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::UnitRange{Int64}, ::Vararg{UnitRange{Int64},N} where N) at /home/long/.julia/v0.6/PyCall/src/PyCall.jl:653
 [5] _pycall(::PyCall.PyObject, ::UnitRange{Int64}, ::Vararg{UnitRange{Int64},N} where N) at /home/long/.julia/v0.6/PyCall/src/PyCall.jl:641
 [6] #pycall#71(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Type{PyCall.PyAny}, ::UnitRange{Int64}, ::Vararg{UnitRange{Int64},N} where N) at /home/long/.julia/v0.6/PyCall/src/PyCall.jl:675
 [7] pycall(::PyCall.PyObject, ::Type{PyCall.PyAny}, ::UnitRange{Int64}, ::Vararg{UnitRange{Int64},N} where N) at /home/long/.julia/v0.6/PyCall/src/PyCall.jl:675
 [8] #plot#85(::Array{Any,1}, ::Function, ::UnitRange{Int64}, ::Vararg{UnitRange{Int64},N} where N) at /home/long/.julia/v0.6/PyPlot/src/PyPlot.jl:172
 [9] plot(::UnitRange{Int64}, ::Vararg{UnitRange{Int64},N} where N) at /home/long/.julia/v0.6/PyPlot/src/PyPlot.jl:169
 [10] macro expansion at ./REPL.jl:97 [inlined]
 [11] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73

julia> PyPlot.plot(1:10,1:10)
1-element Array{PyCall.PyObject,1}:
 PyObject <matplotlib.lines.Line2D object at 0x7fde8c0b1978>
```
The plot renders correctly on the second try, and the window has title "Figure 1".

I am using Archlinux and the following julia, python and matplotlib packages:

```
$ pacman -Qi python
Name                     : python
Version                  : 3.6.3-1
Beschreibung             : Next generation of the python high-level scripting language
Architektur              : x86_64
```

```
$ pacman -Qi julia
Name                     : julia
Version                  : 2:0.6.1-1
Beschreibung             : High-level, high-performance, dynamic programming language
Architektur              : x86_64
```

```
$ pacman -Qi python-matplotlib 
Name                     : python-matplotlib
Version                  : 2.1.0-1
Beschreibung             : A python plotting library, making publication quality plots
Architektur              : x86_64
```

**Comment by pjssilva** [comment] 2017-12-18 23:32
I had the same problem. I found a workaround by using the qt4agg backend with pyside. It looks like it is a problem when mixing Julia and a recent QT5 library. This bug looks like a duplicate of #291.

**Comment by stevengj** [comment] 2017-12-20 15:12
Closing as dup.

**Closed by stevengj** 2017-12-20 15:12 UTC
