### ISSUE TITLE
PyPlot unable to import correct version of matplotlib despite correct path being called by PyCall

### ISSUE THREAD

**Issue by gaomrx** [JuliaPy/PyPlot.jl#357] opened 2018-05-07 22:55 UTC
Correct path for PyCall to call PyPlot 
![image](https://user-images.githubusercontent.com/6380557/39728904-31939a06-5227-11e8-8f15-84ecf1d2a22a.png)

Unable to use PyPlot despite providing correct path
![image](https://user-images.githubusercontent.com/6380557/39728960-7102795a-5227-11e8-9ea3-f98dfb6b7348.png)

Plots is unable to detect installed version of PyPlot 
![image](https://user-images.githubusercontent.com/6380557/39729036-bc1302ca-5227-11e8-9c24-ef08e3095a5b.png)

Current version of python and matplotlib on machine
![image](https://user-images.githubusercontent.com/6380557/39729116-28999e54-5228-11e8-8869-2893604b3cb6.png)

**Comment by stevengj** [comment] 2018-05-08 18:25
Duplicate of #151.

**Closed by stevengj** 2018-05-08 18:25 UTC
