### ISSUE TITLE
MKL error on Mac OSX

### ISSUE THREAD

**Issue by mopg** [JuliaPy/PyPlot.jl#320] opened 2017-10-14 03:01 UTC
Since upgrading to Julia v0.6 (it was working for v0.5), I keep getting an MKL error with PyPlot on my Mac OSX. When I run e.g. `plot([0,1],[0,1])`, I keep getting:

> Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib.

I found some workarounds to remove MKL from conda: https://www.anaconda.com/blog/developer-blog/anaconda-25-release-now-mkl-optimizations/. However, it is not clear to me how to do this for the version that is installed by Julia. 

Any thoughts on how to fix this?

**Comment by stevengj** [comment] 2017-10-14 12:32
Duplicate of #315 ... see there for a workaround.  (This will be fixed in an upcoming Anaconda release.)

**Closed by stevengj** 2017-10-14 12:32 UTC
