### ISSUE TITLE
Strange PyPlot Interaction Gives NaN with QR factorization

### ISSUE THREAD

**Issue by jebej** [JuliaPy/PyPlot.jl#515] opened 2021-01-28 22:16 UTC
I have reduced a weird issue I noticed a little while ago. Displaying a pyplot figure, here, just before the call to `qr`, causes the factorization to return all `NaN`s.

If the figure isn't displayed, which I'm not sure how to do in the REPL, so the below is run in Atom with `display` commented out, the factorization works fine.

If the factorization is rerun, the result is fine as well.

```julia
using PyPlot
fig = figure(1);
x = rand(10,10);
plot(x); xlim(-12,0);
display(fig); # comment out in Atom so fig doesn't show
first(qr(x))[1]
```

**Comment by jebej** [comment] 2021-01-28 22:16
also ref https://github.com/JuliaNLSolvers/LsqFit.jl/issues/176

**Comment by stevengj** [comment] 2021-01-29 20:43
Seems like a duplicate of #477.

Essentially, Matplotlib loads NumPy with loads a BLAS library, and on some systems this is somehow conflicting with Julia's BLAS library.

**Closed by stevengj** 2021-01-29 20:43 UTC
